version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mig_demo
    volumes:
       - ./sql_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
